import React, { useState } from "react";
import { 
  Users, 
  CheckCircle, 
  Activity, 
  Utensils, 
  Heart,
  Eye,
  Hand,
  ArrowRight,
  Bot,
  Sparkles,
  Music,
  Check,
  Loader2,
  Flame,
  Footprints,
  Clock,
  MessageSquare,
  Volume2
} from "lucide-react";
import { HistoryItem, UserSettings, WeatherInfo, CollaborativeSummary } from "../types";
import { motion, AnimatePresence } from "motion/react";

interface HistoryTabProps {
  historyItems: HistoryItem[];
  settings: UserSettings;
  onSendWave: () => void;
  waveSent: boolean;
  weather: WeatherInfo | null;
  speakText: (text: string) => void;
}

export default function HistoryTab({
  historyItems,
  settings,
  onSendWave,
  waveSent,
  weather,
  speakText
}: HistoryTabProps) {
  const [report, setReport] = useState<CollaborativeSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [currentStep, setCurrentStep] = useState(1);

  // Scaled text sizes for senior readability
  const getTextSizeClass = () => {
    if (settings.textSize === "large") return "text-[24px] leading-relaxed";
    if (settings.textSize === "huge") return "text-[28px] leading-relaxed";
    return "text-[18px] leading-relaxed";
  };

  const getSubTextSizeClass = () => {
    if (settings.textSize === "large") return "text-[20px] leading-relaxed";
    if (settings.textSize === "huge") return "text-[24px] leading-relaxed";
    return "text-[16px] leading-relaxed";
  };

  // Quick mapping of items to icons
  const getItemIcon = (type: string) => {
    switch (type) {
      case 'chat':
        return <div className="w-14 h-14 bg-primary-fixed text-on-primary-fixed flex items-center justify-center rounded-2xl flex-shrink-0"><Activity className="w-8 h-8 text-primary" /></div>;
      case 'lunch':
        return <div className="w-14 h-14 bg-secondary-fixed text-on-secondary-fixed flex items-center justify-center rounded-2xl flex-shrink-0"><Utensils className="w-8 h-8 text-secondary" /></div>;
      case 'checkin':
      default:
        return <div className="w-14 h-14 bg-tertiary-fixed text-on-tertiary-fixed flex items-center justify-center rounded-2xl flex-shrink-0"><Heart className="w-8 h-8 text-rose-500 fill-rose-500" /></div>;
    }
  };

  // Call Multi-agent endpoint sequentially
  const generateSummaryReport = async () => {
    setLoading(true);
    setReport(null);
    setCurrentStep(1);

    // Calculate active stats for today from history logs
    const todayWalks = historyItems.filter(item => item.dateLabel === '今日' && item.detail.includes('お散歩'));
    let walkDuration = 0;
    let walkCalories = 0;
    let steps = 0;

    todayWalks.forEach(w => {
      const minMatch = w.detail.match(/お散歩\s*(\d+)分/);
      const calMatch = w.detail.match(/([\d\.]+)\s*kcal/);
      const stepMatch = w.detail.match(/(\d+)\s*歩/);
      if (minMatch) walkDuration += parseInt(minMatch[1], 10);
      if (calMatch) walkCalories += parseFloat(calMatch[1]);
      if (stepMatch) steps += parseInt(stepMatch[1], 10);
    });

    const chatCount = historyItems.filter(item => item.dateLabel === '今日' && item.type === 'chat').length;

    // Orchestrator simulation interval to visualizes multi-agent coordination
    const stepInterval = setInterval(() => {
      setCurrentStep(prev => {
        if (prev < 4) return prev + 1;
        clearInterval(stepInterval);
        return prev;
      });
    }, 1000);

    const startTime = Date.now();

    try {
      const res = await fetch("/api/agents/collaborate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          walkDuration,
          walkCalories,
          chatCount,
          weight: settings.weight || 60,
          weatherCondition: weather?.condition || "晴れ",
          userName: settings.userName
        })
      });
      const data = await res.json();

      // Enforce minimum time for each agent to look nice and show coordination
      const elapsed = Date.now() - startTime;
      const delayNeeded = Math.max(0, 4200 - elapsed);
      
      setTimeout(() => {
        clearInterval(stepInterval);
        setReport(data);
        setLoading(false);
        // Multimodal feature: speak the combined summaries generated by the agents
        const speakParagraph = `今日の報告書ができたにゃ！まず、たまからのメッセージ。「${data.tamaComment || ""}」健康コンシェルジュからは、「${data.healthAdvice?.title || ""}。${data.healthAdvice?.content || ""}」ですにゃ🐾`;
        speakText(speakParagraph);
      }, delayNeeded);

    } catch (err) {
      console.error(err);
      clearInterval(stepInterval);
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8 pb-10">
      {/* Hero Message Section (Family is Watching) */}
      <section className="hand-drawn-border bg-surface-container-low p-6 flex flex-col gap-4 shadow-sm">
        <div className="flex items-center gap-3">
          <Users className="w-10 h-10 text-primary" />
          <h2 className="text-2xl font-black text-on-surface">家族が見守っています</h2>
        </div>
        <p className="text-lg text-on-surface-variant font-bold leading-relaxed">
          ご家族が今日のたまとの会話を確認しました！あなたが元気そうで安心していますよ。
        </p>
        <div className="flex items-center gap-2 text-secondary font-black text-base">
          <CheckCircle className="w-6 h-6 text-secondary" />
          <span>家族4人とつながっています</span>
        </div>
      </section>

      {/* NEW: Multi-Agent Collaboration AI Summary Report */}
      <section className="space-y-4">
        <div className="flex items-center gap-2">
          <Bot className="w-7 h-7 text-primary" />
          <h3 className="text-2xl font-black text-on-surface">今日のAI見守りレポート</h3>
        </div>

        {!loading && !report && (
          <div className="bg-[#FAF5EF] hand-drawn-border p-6 rounded-3xl text-center space-y-4 shadow-sm">
            <div className="flex justify-center gap-2 text-primary font-black text-lg">
              <span>🐾 たまと3つのAIエージェントが、今日一日の活動をまとめますにゃ！</span>
            </div>
            <p className="text-base text-outline font-bold leading-relaxed">
              会話回数やお散歩、天気を踏まえて、健康アドバイス、今日のおすすめ昭和名曲、ご家族への報告書を自動で作ります。
            </p>
            <button
              onClick={generateSummaryReport}
              className="btn-press w-full h-18 bg-primary text-on-primary rounded-2xl border-b-6 border-on-primary-fixed-variant font-black text-xl flex items-center justify-center gap-3 cursor-pointer select-none"
            >
              <Sparkles className="w-6 h-6 animate-pulse" />
              🤖 AI連携レポートを今すぐ作成する
            </button>
          </div>
        )}

        {/* LOADING STATE showing sequential agent collaboration */}
        {loading && (
          <div className="bg-[#FAF5EF] hand-drawn-border p-6 rounded-3xl space-y-6 shadow-md border-primary/20">
            <div className="flex items-center gap-3 text-primary justify-center border-b-2 border-dashed border-outline-variant pb-4">
              <Loader2 className="w-8 h-8 animate-spin" />
              <span className="text-xl font-black animate-pulse">🤖 4つのAIエージェントが連携中…</span>
            </div>

            {/* Step-by-step progress tracking */}
            <div className="space-y-4">
              {/* Step 1: Tama */}
              <div className="flex items-center gap-3">
                <span className={`w-8 h-8 rounded-full flex items-center justify-center border-2 border-outline font-black text-sm ${currentStep >= 1 ? 'bg-[#596332] text-white' : 'bg-white text-outline'}`}>
                  {currentStep > 1 ? <Check className="w-4 h-4 stroke-[3]" /> : "1"}
                </span>
                <span className={`text-base font-black ${currentStep === 1 ? 'text-[#596332] animate-pulse scale-105' : currentStep > 1 ? 'text-outline line-through' : 'text-outline-variant'}`}>
                  🐱 たま（会話）：お疲れ様メッセージの準備にゃ🐾
                </span>
              </div>

              {/* Step 2: Health Concierge */}
              <div className="flex items-center gap-3">
                <span className={`w-8 h-8 rounded-full flex items-center justify-center border-2 border-outline font-black text-sm ${currentStep >= 2 ? 'bg-[#596332] text-white' : 'bg-white text-outline'}`}>
                  {currentStep > 2 ? <Check className="w-4 h-4 stroke-[3]" /> : "2"}
                </span>
                <span className={`text-base font-black ${currentStep === 2 ? 'text-[#596332] animate-pulse scale-105' : currentStep > 2 ? 'text-outline line-through' : 'text-outline-variant'}`}>
                  🔬 健康コンシェルジュ：お体の健康状態・運動の分析中…
                </span>
              </div>

              {/* Step 3: DJ Tama */}
              <div className="flex items-center gap-3">
                <span className={`w-8 h-8 rounded-full flex items-center justify-center border-2 border-outline font-black text-sm ${currentStep >= 3 ? 'bg-[#596332] text-white' : 'bg-white text-outline'}`}>
                  {currentStep > 3 ? <Check className="w-4 h-4 stroke-[3]" /> : "3"}
                </span>
                <span className={`text-base font-black ${currentStep === 3 ? 'text-[#596332] animate-pulse scale-105' : currentStep > 3 ? 'text-outline line-through' : 'text-outline-variant'}`}>
                  🎵 DJエージェント：気分に合う懐メロを検索中（Search）…
                </span>
              </div>

              {/* Step 4: Family Report */}
              <div className="flex items-center gap-3">
                <span className={`w-8 h-8 rounded-full flex items-center justify-center border-2 border-outline font-black text-sm ${currentStep >= 4 ? 'bg-[#596332] text-white' : 'bg-white text-outline'}`}>
                  "4"
                </span>
                <span className={`text-base font-black ${currentStep === 4 ? 'text-[#596332] animate-pulse' : 'text-outline-variant'}`}>
                  ✉️ 家族レポート：ご家族向けの報告書を作成中…
                </span>
              </div>
            </div>
          </div>
        )}

        {/* COMPLETED REPORT CARD (Bento Design) */}
        {!loading && report && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-[#FFFDF9] hand-drawn-border p-6 rounded-3xl space-y-6 shadow-lg border-2 border-primary"
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b-4 border-dashed border-[#E07A5F]/40 pb-4">
              <span className="flex items-center gap-2 bg-[#FAF0E6] text-[#E07A5F] font-black text-xs px-3 py-1.5 rounded-full border-2 border-outline">
                ✨ 4つのAIエージェント共同報告書
              </span>
              <button 
                onClick={generateSummaryReport}
                className="text-xs font-black text-primary underline hover:text-[#596332]"
              >
                新しく作り直す 🔄
              </button>
            </div>

            {/* 1. Tama Dialogue Bubble */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="bg-primary text-on-primary text-[11px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                  🐱 会話・たま
                </span>
                <button
                  onClick={() => speakText(report.tamaComment || "お疲れ様だにゃ！")}
                  className="flex items-center gap-1 bg-[#596332] text-white px-3 py-1 rounded-full text-xs font-black cursor-pointer active:scale-95 border-2 border-outline shadow-sm"
                >
                  <Volume2 className="w-3.5 h-3.5" />
                  <span>声で聞く 🔊</span>
                </button>
              </div>
              <div className="relative flex items-start gap-3 bg-surface-container-low p-4 rounded-2xl border-2 border-outline-variant">
                <div className="w-12 h-12 rounded-full overflow-hidden flex-shrink-0 border border-outline bg-primary-fixed">
                  <img 
                    alt="たま" 
                    className="w-full h-full object-cover scale-110" 
                    src="https://lh3.googleusercontent.com/aida-public/AB6AXuDJzV9W11iBWAN2vK41UvcNTwO1N8vHvdNBneVAmMSRMJjbAVGyTW5kiktYCyMy3swbY9NsA3fNkzpayZKoCmgbNUR93y5HJMFJ7MGqxtSJkHbp-C3bCKDviWfbdMiSVMcFEGXDX2cquxq58NuZQjuL-TxRZSws_Ozym9PYrOxz5gtsVpliUhyJnh3qkB_VPe2GkUK0ZMW6waCXdCQysl3JNuXJixNo6u8wZbRLubpOZBGVAso4DGh9cs2jhRuMKbOKNj3rQW9CTdEc"
                  />
                </div>
                <div>
                  <p className={`${getTextSizeClass()} font-black text-on-surface italic`}>
                    「{(report as any).tamaComment || "お疲れ様だにゃ！"}」
                  </p>
                </div>
              </div>
            </div>

            {/* 2. Health Concierge Card */}
            <div className="p-5 bg-teal-50/50 rounded-2xl border-2 border-teal-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <span className="bg-teal-600 text-white text-[11px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                  🔬 健康コンシェルジュ
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => speakText(`${report.healthAdvice.title}。${report.healthAdvice.content}`)}
                    className="flex items-center gap-1 bg-teal-700 text-white px-3 py-1 rounded-full text-xs font-black cursor-pointer active:scale-95 border-2 border-outline shadow-sm"
                  >
                    <Volume2 className="w-3.5 h-3.5" />
                    <span>声で聞く 🔊</span>
                  </button>
                  <span className={`text-xs font-black px-2 py-0.5 rounded-md border ${
                    report.healthAdvice.priority === 'high' 
                      ? 'bg-rose-100 text-rose-700 border-rose-300' 
                      : 'bg-green-100 text-green-700 border-green-300'
                  }`}>
                    重要度: {report.healthAdvice.priority === 'high' ? '高' : '通常'}
                  </span>
                </div>
              </div>
              <div>
                <h4 className="text-xl font-black text-teal-900 flex items-center gap-1.5">
                  💡 {report.healthAdvice.title}
                </h4>
                <p className={`${getSubTextSizeClass()} font-bold text-teal-800 mt-2`}>
                  {report.healthAdvice.content}
                </p>
              </div>
            </div>

            {/* 3. DJ Tama Song card */}
            <div className="p-5 bg-amber-50/70 rounded-2xl border-2 border-amber-500/30 space-y-4">
              <div className="flex items-center justify-between">
                <span className="bg-amber-600 text-white text-[11px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                  🎵 DJエージェント
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => speakText(`今日の一曲は、${report.song.artist}さんの、${report.song.title}だにゃ！紹介コメントですにゃ。「${report.song.commentary}」`)}
                    className="flex items-center gap-1 bg-amber-700 text-white px-3 py-1 rounded-full text-xs font-black cursor-pointer active:scale-95 border-2 border-outline shadow-sm"
                  >
                    <Volume2 className="w-3.5 h-3.5" />
                    <span>声で聞く 🔊</span>
                  </button>
                  <span className="text-xs font-black text-amber-800">
                    DJたまセレクト
                  </span>
                </div>
              </div>
              
              {/* DJ commentary bubble */}
              <div className="p-3 bg-white/80 rounded-xl border border-dashed border-amber-400">
                <p className="text-base font-bold text-on-surface italic leading-relaxed">
                  「{report.song.commentary}」
                </p>
              </div>

              <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 pt-1">
                <div>
                  <span className="text-[11px] font-black text-outline block">今日の一曲</span>
                  <h4 className="text-2xl font-black text-on-surface leading-tight">
                    {report.song.title}
                  </h4>
                  <p className="text-base font-bold text-amber-700">
                    歌手: {report.song.artist}
                  </p>
                </div>
                <a
                  href={report.song.youtubeUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-press flex items-center justify-center gap-2 bg-[#FF0000] hover:bg-[#CC0000] text-white font-black text-base px-5 py-3 rounded-full border-2 border-outline shadow-md active:scale-95 transition-all text-center select-none"
                >
                  <span>▶</span>
                  この曲を聴く
                </a>
              </div>
            </div>

            {/* 4. Family Report Card */}
            <div className="p-5 bg-orange-50/50 rounded-2xl border-2 border-orange-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <span className="bg-orange-600 text-white text-[11px] font-black px-2 py-0.5 rounded-full uppercase tracking-wider">
                  ✉️ 家族レポート
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => speakText(`家族向けのレポートだにゃ。${report.familyReport.summary}。ご家族へのメッセージは、「${report.familyReport.familyMessage}」だにゃ🐾`)}
                    className="flex items-center gap-1 bg-orange-700 text-white px-3 py-1 rounded-full text-xs font-black cursor-pointer active:scale-95 border-2 border-outline shadow-sm"
                  >
                    <Volume2 className="w-3.5 h-3.5" />
                    <span>声で聞く 🔊</span>
                  </button>
                  <span className="bg-orange-100 text-orange-700 border border-orange-300 text-xs font-black px-2.5 py-0.5 rounded-full">
                    状態: {report.familyReport.healthStatusLabel}
                  </span>
                </div>
              </div>
              <div className="space-y-2">
                <p className="text-xs font-black text-outline">
                  📊 活動まとめ: {report.familyReport.summary}
                </p>
                <div className="bg-white p-3 rounded-xl border border-dashed border-orange-200">
                  <p className="text-base font-bold text-orange-900 leading-relaxed">
                    {report.familyReport.familyMessage}
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </section>

      {/* Family Members Horizontal Scroll */}
      <section>
        <h3 className="text-sm font-black text-outline mb-3 uppercase tracking-wider">最近見てくれた家族</h3>
        <div className="flex gap-4 overflow-x-auto pb-4 no-scrollbar">
          {/* Family Card 1: Sarah */}
          <div className="flex-shrink-0 w-36 bg-surface-container-highest rounded-2xl p-4 flex flex-col items-center gap-2 border-2 border-outline-variant shadow-sm active:translate-y-0.5 transition-transform">
            <div className="relative">
              <div className="w-20 h-20 rounded-full overflow-hidden border-2 border-primary bg-primary-fixed">
                <img 
                  alt="Sarah" 
                  className="w-full h-full object-cover" 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuDIg5MlAnrE3IcjtMJoqqMqWwdweFLot0S0qYEvnQwkl6O6dJHDq5xsujCsI8BG31kfag2gGs1llVfU98fhN8mL4e2UbztPXskuQeSCmoamsurPts9Jcz3ry35huehGSZRw6UylTm36ghYFGzvCum4shyYWisJRStOPtiYyUeY7UGV8CZC0N2LhkDh9yq2h3tXer5F4NbtK14DveAJY1L2JIVYpG4tnuyOwml2I_tSoBwvcdXtkQg3btGArvnnQDYNdEls34EGzDzyO"
                />
              </div>
              <div className="absolute -bottom-1 -right-1 bg-secondary text-on-secondary rounded-full p-1 border-2 border-surface animate-pulse">
                <Eye className="w-4 h-4" />
              </div>
            </div>
            <span className="font-black text-on-surface text-base">Sarah</span>
            <span className="text-xs text-outline font-bold">10分前</span>
          </div>

          {/* Family Card 2: David */}
          <div className="flex-shrink-0 w-36 bg-surface-container-highest rounded-2xl p-4 flex flex-col items-center gap-2 border-2 border-outline-variant shadow-sm active:translate-y-0.5 transition-transform">
            <div className="relative">
              <div className="w-20 h-20 rounded-full overflow-hidden border-2 border-primary bg-primary-fixed">
                <img 
                  alt="David" 
                  className="w-full h-full object-cover" 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuDJPV8CPzrCkcqMGi12x6Hp8QIL6KR9_b4en6jzyrfrnCZPa7xgZ1EAgdfsVST-6uYnAqlVZUJCvBwJwKy-b87zOeRHI2rUYxh0Vm8u5CMVPU9E8j0kbScjm2r5dtlbpMPlhbd82C7qlCIADYZp6F_8N2H7T2GkyY9ArwF2Bpy_wZCD9cQr_h87U1zvvZKQmFQLrr7j6e6tetC8t_tcmjxqiMATKOubUv56Q6nzRlKSmUb8DzvyiAFw0MvbT-_qr5_8f5WRfA2O9NMk"
                />
              </div>
              <div className="absolute -bottom-1 -right-1 bg-secondary text-on-secondary rounded-full p-1 border-2 border-surface">
                <Eye className="w-4 h-4" />
              </div>
            </div>
            <span className="font-black text-on-surface text-base">David</span>
            <span className="text-xs text-outline font-bold">2時間前</span>
          </div>

          {/* Family Card 3: Leo */}
          <div className="flex-shrink-0 w-36 bg-surface-container-highest rounded-2xl p-4 flex flex-col items-center gap-2 border-2 border-outline-variant shadow-sm active:translate-y-0.5 transition-transform">
            <div className="relative">
              <div className="w-20 h-20 rounded-full overflow-hidden border-2 border-primary bg-primary-fixed">
                <img 
                  alt="Leo" 
                  className="w-full h-full object-cover" 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuBF6rDyXj-PeaYYVGWpqGhAKdu63V2vWELyPT4M88T1LRQ_hcW6_Tu4I3_Hao-nSpjZLRcAtLwIldUVh5VnqB5UrCiCrG4WT4LxiMKTiqf18d_QkXOn59f6ONwJ3sWvRdbvWYODZROjvexdcjz2TB1zUeo-0A2kORaXuzUrXfT6nKdOnNZ4uYT5j3ZYs2WQctv9hhTSfZhk3jAYCYhaOv-4w9w1N_LH1JCMiaQIJVwhGPAJbuKH_rm4LQTmZ2mdz6lJ6YLPP0rpixVi"
                />
              </div>
              <div className="absolute -bottom-1 -right-1 bg-secondary text-on-secondary rounded-full p-1 border-2 border-surface">
                <Eye className="w-4 h-4" />
              </div>
            </div>
            <span className="font-black text-on-surface text-base">Leo</span>
            <span className="text-xs text-outline font-bold">今日</span>
          </div>
        </div>
      </section>

      {/* Activity History List */}
      <section className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-2xl font-black text-on-surface">これまでの記録</h3>
          <span className="text-sm font-bold text-outline">活動履歴</span>
        </div>

        <div className="space-y-4">
          {historyItems.map((item) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              className="flex items-start gap-4 p-5 bg-surface-container-low rounded-2xl border-2 border-outline-variant shadow-sm"
            >
              {getItemIcon(item.type)}
              <div className="flex-1">
                <div className="flex justify-between items-start">
                  <p className="font-black text-on-surface text-lg">{item.title}</p>
                  <span className="text-outline font-bold text-xs">{item.timestamp}</span>
                </div>
                <p className="text-on-surface-variant font-bold text-base mt-1 italic">
                  「{item.detail}」
                </p>
                <div className="mt-2 text-xs text-outline font-bold">
                  日付: {item.dateLabel}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Warm Reassuring Action (Send a wave) */}
      <section className="py-4 flex flex-col items-center text-center">
        <div className="bg-primary-container text-on-primary-container p-8 rounded-3xl w-full flex flex-col gap-4 border-4 border-outline">
          <Heart className="w-14 h-14 mx-auto text-white fill-white animate-pulse" />
          <h4 className="text-2xl font-black">家族に合図（あいず）を送る？</h4>
          <p className="text-lg font-bold">あなたも家族のことを想っていると、簡単に知らせることができますよ。</p>
          
          <button 
            onClick={onSendWave}
            disabled={waveSent}
            className={`font-black py-4 px-8 rounded-full shadow-md active:scale-95 transition-all flex items-center justify-center gap-3 mt-2 min-h-[64px] border-2 border-outline cursor-pointer select-none ${waveSent ? 'bg-secondary text-on-secondary border-secondary' : 'bg-white text-primary hover:bg-surface'}`}
          >
            <Hand className={`w-8 h-8 ${waveSent ? '' : 'animate-bounce'}`} />
            <span className="text-xl">
              {waveSent ? '合図を送りました！' : '合図（ウェーブ）を送る'}
            </span>
          </button>
          
          <AnimatePresence>
            {waveSent && (
              <motion.p 
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="text-sm font-bold text-secondary-container mt-2"
              >
                🐾 家族に「元気にしてるにゃ！」と通知を届けました
              </motion.p>
            )}
          </AnimatePresence>
        </div>
      </section>
    </div>
  );
}

